name: Alpha Feedback
description: Report internal alpha feedback with structured triage fields
title: "[alpha][medium] "
labels:
  - feedback:alpha
  - stage:alpha
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting alpha feedback.
        Please fill all required fields so we can triage within one cycle.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Impact on the primary workflow
      options:
        - blocker
        - high
        - medium
        - low
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: How often this happens
      options:
        - always
        - often
        - sometimes
        - once
    validations:
      required: true

  - type: dropdown
    id: impact_area
    attributes:
      label: Impact area
      options:
        - new
        - run
        - dev
        - test
        - check
        - docs
        - perf
        - other
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, uv version
      placeholder: "Ubuntu 24.04, Python 3.12.12, uv 0.5.x"
    validations:
      required: true

  - type: textarea
    id: commands
    attributes:
      label: Commands run
      description: Paste exact commands
      placeholder: |
        pyqck new myapi --profile api --template fastapi
        uv sync --extra dev
        pyqck dev
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Key output
      description: Include ERROR/Hint lines and relevant logs
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Minimal reproduction steps
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional notes
      description: Optional mitigation ideas or context
    validations:
      required: false
