from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from pyqck.scaffold.names import normalize_package_name


@dataclass(slots=True, frozen=True)
class CLITemplateContext:
    project_name: str
    package_name: str
    profile: str = "cli"
    template: str = "baseline-cli"

    @classmethod
    def from_project_name(cls, project_name: str) -> CLITemplateContext:
        return cls(project_name=project_name, package_name=normalize_package_name(project_name))


def build_cli_template(context: CLITemplateContext) -> dict[Path, str]:
    src_package = Path("src") / context.package_name
    test_module = Path("tests") / f"test_{context.package_name}.py"

    return {
        Path(".gitignore"): _gitignore(),
        Path("README.md"): _readme(context),
        Path("pyproject.toml"): _pyproject(context),
        Path("pyquick.toml"): _pyquick_toml(context),
        src_package / "__init__.py": _package_init(),
        src_package / "main.py": _main_module(),
        test_module: _test_module(context),
    }


def _gitignore() -> str:
    return """.venv/
__pycache__/
.pytest_cache/
.ruff_cache/
.pyright/
build/
dist/
*.pyc
*.egg-info/
"""


def _readme(context: CLITemplateContext) -> str:
    return f"""# {context.project_name}

Generated by PyQuick using the Python CLI profile.

## Quickstart

```bash
pyqck install
pyqck test
pyqck check
```

Note: profile-aware `pyqck run`/`pyqck dev` behavior for CLI projects is tracked in issue #34.

## Project layout

- `src/{context.package_name}/main.py`: CLI entrypoint
- `tests/test_{context.package_name}.py`: baseline unit test
- `pyquick.toml`: PyQuick command defaults
"""


def _pyproject(context: CLITemplateContext) -> str:
    project_slug = context.project_name.strip().replace(" ", "-").lower()
    return f"""[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[project]
name = "{project_slug}"
version = "0.1.0"
description = "Python CLI generated by PyQuick"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
dev = [
  "pyright>=1.1.390",
  "pytest>=8.3.0",
  "ruff>=0.8.0",
]

[project.scripts]
{context.package_name} = "{context.package_name}.main:main"

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-q"
testpaths = ["tests"]

[tool.ruff]
target-version = "py312"
line-length = 100
src = ["src", "tests"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]

[tool.hatch.build.targets.wheel]
packages = ["src/{context.package_name}"]
"""


def _pyquick_toml(context: CLITemplateContext) -> str:
    return f"""[project]
name = "{context.project_name}"
profile = "{context.profile}"
template = "{context.template}"

[tooling]
packaging = "uv"
linting = "ruff"
testing = "pytest"
typing = "pyright"
running = "python"

[checks]
pipeline = ["lint", "type", "test"]
stop_on_first_failure = true

[dev]
reload = true
watch = ["src", "tests"]
debounce_ms = 200
checks_mode = "incremental"
fallback_threshold = 8
"""


def _package_init() -> str:
    return ""


def _main_module() -> str:
    return """def main() -> int:
    print("hello from pyqck cli profile")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
"""


def _test_module(context: CLITemplateContext) -> str:
    return f"""from {context.package_name}.main import main


def test_main_returns_zero() -> None:
    assert main() == 0
"""
